"sb2" script: fail if failed to create session directory
- catches an error if /tmp is full...

diff --git a/utils/sb2 b/utils/sb2
--- a/utils/sb2
+++ b/utils/sb2
@@ -836,6 +836,10 @@ function initialize_new_sb2_session()
 	# Create session directories
 	date_and_time_now=`date +%Y%m%d-%H%M%S`
 	SBOX_SESSION_DIR=`mktemp -d /tmp/sb2-$USER-$date_and_time_now.XXXXXX`
+	if [ $? != 0 ]; then
+		echo "Failed to create directory for session (problems with /tmp ?) " >&2
+		exit 1
+	fi
 
 	mkdir -p $SBOX_SESSION_DIR
 	mkdir $SBOX_SESSION_DIR/tmp
