Add sb2-config, rework target setup
Targets no longer have any extra files in them, everything
lives under ~/.scratchbox2.

Per-target sb2 files go to ~/.scratchbox2/TARGETNAME

sb2-config can be used to list the available targets and to set
the default target.

Signed-off-by: Lauri Leukkunen <lle@rahina.org>

diff --git a/utils/sb2 b/utils/sb2
--- a/utils/sb2
+++ b/utils/sb2
@@ -21,8 +21,7 @@ Options:
     -v           display version
     -d           debug mode: log all redirections
     -h           print this help
-    -t DIRECTORY target directory, else search up in directory
-                 structure for a .sb2rc
+    -t TARGET    target to use, use sb2-config -d TARGET to set a default
     -e           emulation mode
     -m MODE      use mapping mode MODE
     -s DIRECTORY load mapping scripts from alternative location
@@ -50,31 +49,27 @@ function sanity_check()
 	# check that most important host and target files exist
 }
 
-find_target_root()
-{
-(
-	while [ "$PWD" != "/" ]; do
-		if [ -r sb2.config ]; then
-			echo "$(readlink -f -n $PWD)"
-			return 0
-		else
-			cd ..
-		fi
-	done
-	return 1
-)
-}
-
 function sboxify_environment()
 {
-
-	if [ -r ~/.sb2rc ]; then
-		. ~/.sb2rc
+	if [ -r ~/.scratchbox2/config ]; then
+		. ~/.scratchbox2/config
 	fi
 
-	if [ -z "$SBOX_TARGET_ROOT" ]; then
-		SBOX_TARGET_ROOT=`find_target_root` || exit_error "Cannot find target root!"
+	if [ -z "$SBOX_TARGET" ]; then
+		SBOX_TARGET=$DEFAULT_TARGET
 	fi
+
+	if [ -z "$SBOX_TARGET" ]; then
+		echo "No target specified and none set as default, aborting."
+		exit 2
+	fi
+
+	if [ ! -e ~/.scratchbox2/$SBOX_TARGET/sb2.config ]; then
+		echo "Invalid target specified, aborting."
+		exit 2
+	fi
+	export SBOX_TARGET
+	. ~/.scratchbox2/$SBOX_TARGET/sb2.config
 
 	if [ -n "$SBOX_DIR" ]; then
 		LD_LIBRARY_PATH=$SBOX_DIR/lib/libsb2:$SBOX_DIR/lib64/libsb2:$SBOX_DIR/lib32/libsb2
@@ -84,14 +79,7 @@ function sboxify_environment()
 		fi
 		SBOX_GCCWRAPPER="$SBOX_DIR/bin/sb_gcc_wrapper"
 	else
-		exit_error "Something foul happeninged..."
-	fi
-
-	if [ -n "$SBOX_TOOLS_ROOT" ]; then
-		REDIR_LD_SO="$SBOX_TOOLS_DIR/lib/ld-linux.so.2"
-		REDIR_LD_LIBRARY_PATH="$SBOX_TOOLS_DIR/lib:$SBOX_TOOLS_DIR/usr/lib:$SBOX_TOOLS_DIR/usr/local/lib"
-
-		export REDIR_LD_SO REDIR_LD_LIBRARY_PATH SBOX_TOOLS_ROOT
+		exit_error "Incorrect target config in ~/.scratchbox2/$SBOX_TARGET/sb2.config"
 	fi
 
 	export LD_LIBRARY_PATH SBOX_LIBSB2 SBOX_REDIR_SCRIPTS SBOX_TARGET_ROOT SBOX_GCCWRAPPER SBOX_TARGET_COMPILER
@@ -99,18 +87,16 @@ function sboxify_environment()
 	# -Riku: I don't think we want to run this on every sb2 invocation..
 	HOST_GCC_INC_DIR=$(echo "#include <stdio.h>" | gcc -M -E - | perl -e 'while(<STDIN>) { $foo{$1} = 1 if m/\/usr([^[:space:]]*\/include)/;}; foreach my $k (keys %foo) {print " -isystem $ENV{SBOX_DIR}/share/scratchbox2/host_usr$k"};')
 
-	export PATH=$SBOX_TARGET_ROOT/sb_tools/bin:$SBOX_DIR/share/scratchbox2/scripts:$SBOX_DIR/bin:$PATH:$SBOX_TARGET_ROOT/bin:$SBOX_TARGET_ROOT/usr/bin:$SBOX_TARGET_ROOT/usr/local/bin:/sbin:/usr/sbin
+	export PATH=$HOME/.scratchbox2/$SBOX_TARGET/bin:$SBOX_DIR/share/scratchbox2/scripts:$SBOX_DIR/bin:$PATH:/sbin:/usr/sbin:$SBOX_TARGET_ROOT/bin:$SBOX_TARGET_ROOT/usr/bin:$SBOX_TARGET_ROOT/usr/local/bin
 
 	export LD_PRELOAD=$SBOX_LIBSB2
 	export SBOX_EXTRA_HOST_COMPILER_ARGS="$HOST_GCC_INC_DIR"
 	export SBOX_EXTRA_CROSS_COMPILER_ARGS="--sysroot=$SBOX_TARGET_ROOT"
-	export SBOX_SCRATCHBOX_CONFIG=$SBOX_TARGET_ROOT/sb2.config
+	export SBOX_SCRATCHBOX_CONFIG=$HOME/.scratchbox2/$SBOX_TARGET/sb2.config
 	export PS1="[SB2] \u@\h \w \$ "
 
-	. $SBOX_SCRATCHBOX_CONFIG
-
 	# Debian exports REVISIT on dpkg 1.14
-	if [ $SBOX_CPU = "arm" ]; then
+	if [ "$SBOX_CPU" = "arm" ]; then
 		export DEB_BUILD_ARCH=armel
 	else
 		export DEB_BUILD_ARCH=$SBOX_CPU
@@ -146,7 +132,7 @@ do
 	(v) version ;;
 	(d) export SBOX_MAPPING_DEBUG=1 ;;
 	(h) usage ;;
-	(t) export SBOX_TARGET_ROOT=$OPTARG ;;
+	(t) export SBOX_TARGET=$OPTARG ;;
 	(e) export SBOX_MAPMODE=emulate ;;
 	(m) export SBOX_MAPMODE=$OPTARG ;;
 	(s) export SBOX_REDIR_SCRIPTS=$OPTARG;;
diff --git a/utils/sb2-init b/utils/sb2-init
--- a/utils/sb2-init
+++ b/utils/sb2-init
@@ -3,61 +3,48 @@
 # Licensed under GPL version 2
 
 
-SBOX_DIR=$(readlink -f $(dirname $_)/..)
-
-if [[ "$1" = "" || "$1" = "--help" ]]; then
-	echo "Usage: sb2-init [compiler]"
-	echo "example: sb2-init arm-linux-gcc"
-	exit 0
-fi
-
-GCC=$1
-
-GCC_FULLPATH=$(which $GCC)
-# test that gcc exists and can be executed
-if [ $? != 0 ]; then
-	echo "$GCC doesn't exist"
-	exit 1
-fi
-GCC_PATH=$(dirname $(which $GCC))
-if [ $GCC -v > /dev/null 2>&1 != 0 ]; then
-	echo "Invalid compiler specified: $GCC"
-	exit 1
-fi
-
-GCC_PREFIX=$(basename $GCC | sed 's/-gcc$/-/')
-ARCH=$($GCC -dumpmachine | awk -F- '{ print $1 }')
-
-case "$ARCH" in
-	arm*)
-		SBOX_OS=none-linux-gnueabi
-		;;
-	ppc*)
-		SBOX_OS=none-linux-gnu
-		;;
-	mips*)
-		SBOX_OS=none-linux-gnu
-		;;
-	*)
-		echo "Unsupported target architecture: $ARCH"
-		echo "You must add support for it into preload/sb_exec.c"
-		echo "and utils/sb2-init"
-		exit 1
-		;;
-
-esac
-
-QEMU=$(which qemu-$ARCH)
-if [ $? != 0 ]; then
-	echo "You don't have qemu-$ARCH installed."
-	exit 1
-fi
-
-function write_sb2config()
+function usage()
 {
-	cat - > sb2.config <<EOF
+	cat <<EOF
+sb2-init - initialize a target root for scratchbox2
+Usage:
+	sb2-init [OPTION]... [TARGETNAME] [COMPILER]
+
+sb2-init is expected to be run in the directory you want
+to use as scratchbox 2 target root.
+
+TARGETNAME is what you want to call this target
+COMPILER is of the form $HOME/arm-2006q3/bin/arm-linux-gcc
+
+
+Options:
+    -c [qemu | sbrsh] select cpu transparency method, qemu is default
+    -d                set target as default scratchbox2 target
+    -h                print this help
+    -n                don't build libtool for the target
+    -s                skip checks for target root's /usr/include etc.
+    -v                display version
+
+Examples:
+    sb2-init ARM arm-linux-gcc
+    sb2-init -sn -c sbrsh armel-debian /path/to/arm-linux-gcc
+EOF
+	exit 2
+}
+
+function version()
+{
+	cat $SBOX_DIR/share/scratchbox2/version
+	exit 0
+}
+
+
+function write_target_config()
+{
+	cat - > $HOME/.scratchbox2/$TARGET/sb2.config <<EOF
 # Scratchbox2 configuration file generated by sb2-init.
 
+SBOX_TARGET_ROOT=$SBOX_TARGET_ROOT
 SBOX_CPU=$ARCH
 SBOX_OS=$SBOX_OS
 SBOX_CPUTRANSPARENCY_METHOD=$QEMU
@@ -103,30 +90,120 @@ function check_buildroot_sanity()
 	if [ $a_ok == 1 ]; then
 		true
 	else
-		false
-	fi
-}
-
-check_buildroot_sanity
-if [ $? != 0 ]; then
-	echo "Your buildroot seems to lack basic essentials like headers 
+		echo "Your buildroot seems to lack basic essentials like headers 
 or c-library. You should probably get either a ready rootfs tarball or
 copy the necessary files from your toolchain into place. After doing that
 you can re-run this script."
+		exit 1
+	fi
+}
+
+SBOX_DIR=$(readlink -f $(dirname $_)/..)
+
+set_as_default=0
+cputransparency=qemu
+with_libtool=1
+skip_checks=false
+
+if [ -z "$*" ]; then
+	usage
+fi
+
+while getopts c:dhnsv foo
+do
+	case $foo in
+	(c) cputransparency=$OPTARG ;;
+	(d) set_as_default=1 ;;
+	(h) usage ;;
+	(n) with_libtool=0 ;;
+	(s) skip_checks=true ;;
+	(v) version ;;
+	(*) usage ;;
+	esac
+done
+shift $(($OPTIND - 1))
+
+TARGET=$1
+SBOX_TARGET_ROOT=$PWD
+GCC=$2
+
+
+GCC_FULLPATH=$(which $GCC)
+# test that gcc exists and can be executed
+if [ $? != 0 ]; then
+	echo "$GCC doesn't exist"
+	exit 1
+fi
+GCC_PATH=$(dirname $(which $GCC))
+if [ $GCC -v > /dev/null 2>&1 != 0 ]; then
+	echo "Invalid compiler specified: $GCC"
 	exit 1
 fi
 
-mkdir -p sb_tools/bin
-write_sb2config
+GCC_PREFIX=$(basename $GCC | sed 's/-gcc$/-/')
+ARCH=$($GCC -dumpmachine | awk -F- '{ print $1 }')
 
-$SBOX_DIR/bin/sb2 -t $PWD $SBOX_DIR/bin/sb2-build-libtool
+case "$ARCH" in
+	arm*)
+		SBOX_OS=none-linux-gnueabi
+		;;
+	ppc*)
+		SBOX_OS=none-linux-gnu
+		;;
+	mips*)
+		SBOX_OS=none-linux-gnu
+		;;
+	*)
+		echo "Unsupported target architecture: $ARCH"
+		echo "You must add support for it into preload/sb_exec.c"
+		echo "and utils/sb2-init"
+		exit 1
+		;;
 
-if [ $? == 0 ]; then
-	echo "sb2-init completed successfully, have fun!"
-else
-	echo "Running $SBOX_DIR/bin/sb2-build-libtool failed"
-	echo "You can run this manually later, otherwise your"
-	echo "sb2 environment is correctly setup and ready to use"
+esac
+
+
+QEMU=$(which qemu-$ARCH)
+if [ ! $skip_checks -a $? != 0 ]; then
+	echo "You don't have qemu-$ARCH installed."
+	exit 1
+fi
+
+if [ -z "$GCC" -o -z "$TARGET" ]; then
+	usage
+	exit 1
+fi
+
+if [ ! $skip_checks ]; then
+	check_buildroot_sanity
 fi
 
 
+
+
+mkdir -p $HOME/.scratchbox2
+
+if [ -z "$(sb2-config -l)" ]; then
+# force this as default anyway as there are no
+# other existing targets
+	set_as_default=1
+fi
+
+mkdir -p $HOME/.scratchbox2/$TARGET/bin
+write_target_config
+
+if [ $set_as_default == 1 ]; then
+	sb2-config -d $TARGET
+fi
+
+if [ $with_libtool == 1 ]; then
+	$SBOX_DIR/bin/sb2 -t $TARGET $SBOX_DIR/bin/sb2-build-libtool
+
+	if [ $? == 0 ]; then
+		echo "sb2-init completed successfully, have fun!"
+	else
+		echo "Running $SBOX_DIR/bin/sb2-build-libtool failed"
+		echo "You can run this manually later, otherwise your"
+		echo "sb2 environment is correctly setup and ready to use"
+	fi
+fi
