SB2's Configuration & Initialization Redesign: part 1
Motivation: sb2's per-target configuration files will be split to smaller
files (one or more / subsystem) to make it possible to
a) reconfigure parts of the system, without doing a full re-initialization
   with sb2-init and
b) to make it possible to upgrade parts of the configuration automatically
   (previously, a full reinitialization (by sb2-init) has been mandatory
   always when the configuration file format has been changed)

This commit introduces some changes to the configuration infrastructure
that are needed in the future; the old config file system is still used for
all real configuration variables.

First, there are two new helper scripts:
- "sb2-upgrade-config" is called automatically by the "sb2" script whenever
  configuration files need to be updated.
- "sb2-parse-sb2-init-args" is now used to parse the command line of "sb2-init";
  this script is needed by "sb2-upgrade-config", too.

Second, "sb2-init" has changes: in addition to the argument processing, some
checks have been re-ordered etc, but there are no real, functional changes

Third, a configuration log was added. The idea is that every time when the
configuration is changed (by any component, either manually or automatically)
the change should be logged. The log can be displayed by sb2-config (a new
option was added to that)

diff --git a/utils/sb2 b/utils/sb2
--- a/utils/sb2
+++ b/utils/sb2
@@ -128,14 +128,38 @@ function set_and_check_SBOX_TARGET()
 	fi
 }
 
+function load_configuration()
+{
+	#-----------
+	# part of the configuration is still stored in the "old format"
+	# configuration file, "sb2.config". It is created by "sb2-init"
+
+	. ~/.scratchbox2/$SBOX_TARGET/sb2.config
+	# Remember where SBOX_TARGET_ROOT was in the configuration file
+	SBOX_TARGET_ROOT_in_config_file=$SBOX_TARGET_ROOT
+
+	#-----------
+	# "New" config system stores configuration to various files
+	# in sb2.config.d directory, and the configuration is automatically
+	# upgraded whenever needed:
+	
+	# check if we need to upgrade configuration:
+	if [ ! -f ~/.scratchbox2/$SBOX_TARGET/sb2.config.d/config-stamp.10 ]; then
+		$SBOX_DIR/share/scratchbox2/scripts/sb2-upgrade-config \
+			$SBOX_TARGET
+		if [ $? != 0 ]; then
+			echo "Failed to upgrade configuration files" >&2
+			exit 1
+		fi
+	fi
+}
+
 function sboxify_environment()
 {
 	LD_LIBRARY_PATH=$SBOX_DIR/lib/libsb2:$SBOX_DIR/lib64/libsb2:$SBOX_DIR/lib32/libsb2:/emul/lib64/libsb2:/emul/lib32/libsb2
 	SBOX_LIBSB2="libsb2.so.1"
 	
-	. ~/.scratchbox2/$SBOX_TARGET/sb2.config
-	# Remember where SBOX_TARGET_ROOT was in the configuration file
-	SBOX_TARGET_ROOT_in_config_file=$SBOX_TARGET_ROOT
+	load_configuration
 
 	# override SBOX_TOOLS_ROOT if requested by command-line option
 	if [ -n "$SBOX_FORCED_TOOLS_ROOT" ]; then
diff --git a/utils/sb2-init b/utils/sb2-init
--- a/utils/sb2-init
+++ b/utils/sb2-init
@@ -10,6 +10,13 @@ if [ $(basename $my_path) != $(basename $0) ]; then
 	fi
 fi
 
+function log_config_action()
+{
+	tstamp=`/bin/date '+%Y-%m-%d %H:%M:%S'`
+	echo "$tstamp	$*" >>$SBOX_CONFIG_DIR/CONFIG-LOG
+}
+
+# Get the original arguments that were specified to sb2-init from
 function show_existing_config_info()
 {
 	has_targets="no"
@@ -23,12 +30,16 @@ function show_existing_config_info()
 			targetdir=`dirname $f`
 			targetname=`basename $targetdir`
 			echo "Target $targetname:"
-			if [ "$SBOX_CONFIG_VERSION" -lt 5 ]; then
-				echo "(configuration file version too old)"
+			if [ -d "$SBOX_TARGET_ROOT" ]; then
+				if [ "$SBOX_CONFIG_VERSION" -lt 5 ]; then
+					echo "(configuration file version too old)"
+				else
+					echo "configured at $SBOX_INIT_TIME by $SBOX_INIT_ID, with command"
+					echo "( cd $SBOX_TARGET_ROOT;"
+					echo "sb2-init $SBOX_INIT_ORIG_ARGS )"
+				fi
 			else
-				echo "configured at $SBOX_INIT_TIME by $SBOX_INIT_ID, with command"
-				echo "( cd $SBOX_TARGET_ROOT;"
-				echo "sb2-init $SBOX_INIT_ORIG_ARGS )"
+				echo "(out of order - target root directory does not exist)"
 			fi
 			echo
 		fi
@@ -85,15 +96,17 @@ function version()
 	exit 0
 }
 
-
+# Create the old-style configuration file.
+# TODO: This system will be replaced by smaller configuration files 
+# that live in $SBOX_CONFIG_DIR directory.
 function write_target_config()
 {
 	cat - > $HOME/.scratchbox2/$TARGET/sb2.config <<EOF
 # Scratchbox2 configuration file generated by sb2-init.
 
 SBOX_INIT_ORIG_ARGS="$SBOX_INIT_ORIG_ARGS"
-SBOX_INIT_TIME=$SBOX_INIT_TIME
-SBOX_INIT_ID="$SBOX_INIT_ID"
+SBOX_INIT_TIME=$SB2INIT_INIT_TIME
+SBOX_INIT_ID="$SB2INIT_INIT_ID"
 
 SBOX_CONFIG_VERSION=9
 
@@ -101,7 +114,7 @@ SBOX_TARGET_ROOT=$SBOX_TARGET_ROOT
 
 SBOX_CPU=$ARCH
 SBOX_GCC_TARGET=$GCC_TARGET
-SBOX_CPUTRANSPARENCY_METHOD="$CPUTRANSP"
+SBOX_CPUTRANSPARENCY_METHOD="$SB2INIT_CPUTRANSP"
 SBOX_UNAME_MACHINE=$ARCH
 
 SBOX_DEFAULT_GCC_PREFIX=$GCC_PREFIX
@@ -147,7 +160,7 @@ if [ -z "\$SBOX_MAPMODE" ]; then
 	SBOX_MAPMODE=$MAPPING_MODE
 fi
 
-SBOX_TOOLS_ROOT=$TOOLS_ROOT
+SBOX_TOOLS_ROOT=$SB2INIT_TOOLS_ROOT
 
 if [ -n "\$SBOX_TOOLS_ROOT" ]; then
 	LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/:/usr/lib64:/lib:/lib64:\$SBOX_TOOLS_ROOT/usr/lib/libfakeroot:\$SBOX_TOOLS_ROOT/usr/lib64/libfakeroot:\$SBOX_TOOLS_ROOT/usr/lib32/libfakeroot:\$LD_LIBRARY_PATH
@@ -164,9 +177,9 @@ function write_sbrsh_config()
 	cat - > $HOME/.scratchbox2/$TARGET/sbrsh.config <<EOF
 # sbrsh configuration file generated by sb2-init.
 
-$TARGET  $REMOTEHOST
-  nfs   $LOCALHOST:$SBOX_TARGET_ROOT  /  rw,nolock,noac,tcp
-  nfs   $LOCALHOST:$HOME  $HOME  rw,nolock,noac,tcp
+$TARGET  $SB2INIT_REMOTEHOST
+  nfs   $SB2INIT_LOCALHOST:$SBOX_TARGET_ROOT  /  rw,nolock,noac,tcp
+  nfs   $SB2INIT_LOCALHOST:$HOME  $HOME  rw,nolock,noac,tcp
   bind  /tmp      /tmp
   bind  /proc     /proc
   bind  /sys      /sys
@@ -209,67 +222,77 @@ you can re-run this script."
 if [ -z "$SBOX_DIR" ]; then
 	SBOX_DIR=$(readlink -f $(dirname $(readlink -f $my_path))/..)
 fi
+SBOX_SHARE_DIR=$SBOX_DIR/share/scratchbox2
 
-# SBOX_INIT_* variables are used to record who initialized, and when and 
-# how sb2 was initialized.
-# It is possible to set SBOX_INIT_ID externally (for example, if
-# another program is used to initialize the system)
 SBOX_INIT_ORIG_ARGS="$*"
-SBOX_INIT_TIME=`date +%Y-%m-%d_%H:%M:%S`
-if [ -z "$SBOX_INIT_ID" ]; then
-	SBOX_INIT_ID="user '$USER'"
-fi
 
-REMOTEHOST=
-LOCALHOST=
-
-set_as_default=0
-with_libtool=1
-with_locales=1
-skip_checks=false
-
-SBOX_EXTRA_CROSS_COMPILER_ARGS=""
-
-if [ -z "$*" ]; then
+# No parameters => show usage and exit.
+if [ -z "$SBOX_INIT_ORIG_ARGS" ]; then
 	usage
 fi
 
-while getopts A:c:C:r:l:m:dhnNst:v foo
-do
-	case $foo in
-	(A) ARCH=$OPTARG ;;
-	(c) CPUTRANSP=$OPTARG ;;
-	(r) REMOTEHOST=$OPTARG ;;
-	(l) LOCALHOST=$OPTARG ;;
-	(d) set_as_default=1 ;;
-	(h) usage ;;
-	(m) MAPPING_MODE=$OPTARG ;;
-	(n) with_libtool=0 ;;
-	(N) with_locales=0 ;;
-	(s) skip_checks=true ;;
-	(t) TOOLS_ROOT=$OPTARG ;;
-	(v) version ;;
-	(C) SBOX_EXTRA_CROSS_COMPILER_ARGS="$SBOX_EXTRA_CROSS_COMPILER_ARGS $OPTARG " ;;
-	(*) usage ;;
-	esac
-done
-shift $(($OPTIND - 1))
+# Parse parameters (round 1); don't write anything to the config directory yet,
+# because a) name of the target is currently unknown, b) there might be 
+# errors in the parameters, or c) if the user is just requesting help or
+# version and we are not actually going to configure anything.
+eval `$SBOX_SHARE_DIR/scripts/sb2-parse-sb2-init-args $SBOX_INIT_ORIG_ARGS`
 
-if [ "$LOCALHOST" ] && [ -z "$REMOTEHOST" ]; then
-	echo "Warning: Local host specified without remote host."
+TARGET=$SB2INIT_TARGET
+SBOX_TARGET_ROOT=$SB2INIT_TARGET_ROOT
+GCC=$SB2INIT_COMPILERS
+
+MAPPING_MODE=$SB2INIT_MAPPING_MODE
+SBOX_EXTRA_CROSS_COMPILER_ARGS=$SB2INIT_SBOX_EXTRA_CROSS_COMPILER_ARGS
+
+# ---------- Check parameters
+
+if [ "$SB2INIT_SHOW_USAGE" == 1 -o "$SB2INIT_ERROR" == 1 ]; then
+	usage
 fi
 
-TARGET=$1
-SBOX_TARGET_ROOT=$PWD
-GCC=$2
+if [ "$SB2INIT_SHOW_VERSION" == 1 ]; then
+	version
+fi
+
+if [ "$SB2INIT_LOCALHOST" ] && [ -z "$SB2INIT_REMOTEHOST" ]; then
+	echo "Warning: Local host specified without remote host."
+fi
 
 if [ -z "$TARGET" ]; then
 	echo "Error: no target given"
 	exit 1
 fi
 
+if [ -z "$MAPPING_MODE" ]; then
+	MAPPING_MODE="simple"
+	echo "Warning: Mapping mode not specified, using default ($MAPPING_MODE)"
+fi
+
+if [ ! -d $SBOX_DIR/share/scratchbox2/lua_scripts/pathmaps/$MAPPING_MODE ]; then
+	echo "Invalid mapping mode: $MAPPING_MODE"
+	exit 1
+fi
+
+# ---------- end of parameter checks
+
+mkdir -p $HOME/.scratchbox2/$TARGET
+
+SBOX_CONFIG_DIR=~/.scratchbox2/$TARGET/sb2.config.d 
+if [ ! -d $SBOX_CONFIG_DIR ]; then
+        mkdir $SBOX_CONFIG_DIR 
+fi
+log_config_action "sb2-init $SBOX_INIT_ORIG_ARGS"
+
+# Parse parameters (round 2); store parameters to the config directory.
+# "$SBOX_CONFIG_DIR/sb2-init-args" can be overwritten by sb2-init or
+# sb2-upgrade-config; the config log should identify who did what..
+$SBOX_SHARE_DIR/scripts/sb2-parse-sb2-init-args $SBOX_INIT_ORIG_ARGS \
+	>$SBOX_CONFIG_DIR/sb2-init-args
+
 if [ -z "$GCC" ]; then
 	echo "Warning: no compiler given"
+	ARCH=$SB2INIT_ARCH
+	echo "Target architecture set to '$ARCH'"
 else
 	GCC_FULLPATH=$(which $GCC)
 	# test that gcc exists and can be executed
@@ -290,12 +313,13 @@ else
 	SBOX_CROSS_GCC_SHORTVERSION=`echo $SBOX_CROSS_GCC_VERSION |
 		sed -e 's/^\([0-9][0-9]*\.[0-9][0-9]*\)\..*/\1/'`
 
-	if [ -z "$ARCH" ]; then
+	if [ -z "$SB2INIT_ARCH" ]; then
 		echo "Using $GCC to detect target architecture:"
 		ARCH=$($GCC -dumpmachine | awk -F- '{ print $1 }')
 		GCC_TARGET=$($GCC -dumpmachine)
 	else
-		echo "Target architecture set to $ARCH"
+		ARCH=$SB2INIT_ARCH
+		echo "Target architecture set to '$ARCH'"
 	fi
 fi
 
@@ -326,7 +350,7 @@ case "$ARCH" in
 	i586*) ;;
 	i686*) ;;
 	*)
-		echo "Unsupported target architecture: $ARCH"
+		echo "Unsupported target architecture: '$ARCH'"
 		echo "You must add support for it into preload/sb_exec.c"
 		echo "and utils/sb2-init"
 		exit 1
@@ -356,34 +380,24 @@ if [ -f $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE ]; then
 	. $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE "initializing"
 fi
 
-if [ -z "$MAPPING_MODE" ]; then
-	MAPPING_MODE="simple"
-fi
 
-if [ ! -d $SBOX_DIR/share/scratchbox2/lua_scripts/pathmaps/$MAPPING_MODE ]; then
-	echo "Invalid mapping mode: $MAPPING_MODE"
-	exit 1
-fi
-
-
-if [ ! $skip_checks ]; then
+if [ ! $SB2INIT_SKIP_CHECKS ]; then
 	check_buildroot_sanity
 fi
-
 
 mkdir -p $HOME/.scratchbox2
 
 if [ -z "$(sb2-config -l)" ]; then
-# force this as default anyway as there are no
-# other existing targets
-	set_as_default=1
+	# force this as default anyway as there are no
+	# other existing targets
+	SB2INIT_SET_AS_DEFAULT=1
 fi
 
-if [ -n "$TOOLS_ROOT" ]; then
-	if [ -e "$TOOLS_ROOT/etc/scratchbox-version" ]; then
+if [ -n "$SB2INIT_TOOLS_ROOT" ]; then
+	if [ -e "$SB2INIT_TOOLS_ROOT/etc/scratchbox-version" ]; then
 		# this is a scratchbox 1.x directory, tread carefully
 		# sb1 is not FHS, *sigh*
-		TOOLS_ROOT=$TOOLS_ROOT/tools
+		SB2INIT_TOOLS_ROOT=$SB2INIT_TOOLS_ROOT/tools
 	fi
 	# else assume standard FHS system
 fi
@@ -411,17 +425,17 @@ HOST_GCC_INC=$(echo "#include <stdio.h>" | gcc -M -E - | SBOX_DIR=$SBOX_DIR perl
 mkdir -p $HOME/.scratchbox2/$TARGET/bin
 write_target_config
 
-if [ -n "$REMOTEHOST" ]; then
-	if [ -z "$LOCALHOST" ]; then
-		LOCALHOST=$(ip -f inet -o addr \
+if [ -n "$SB2INIT_REMOTEHOST" ]; then
+	if [ -z "$SB2INIT_LOCALHOST" ]; then
+		SB2INIT_LOCALHOST=$(ip -f inet -o addr \
 			| awk -- '/: eth[0-9]/ { print $4; exit }' \
 			| cut -d/ -f1)
-		echo "Using NFS server address: $LOCALHOST"
+		echo "Using NFS server address: $SB2INIT_LOCALHOST"
 	fi
 	write_sbrsh_config
 fi
 
-if [ $set_as_default == 1 ]; then
+if [ $SB2INIT_SET_AS_DEFAULT == 1 ]; then
 	sb2-config -d $TARGET
 fi
 
@@ -433,19 +447,20 @@ fi
 # We do the same check for tools here and generate necessary
 # localization files if they are missing.
 #
-if [ $with_locales == 1 ]; then
-	if [ -n "$TOOLS_ROOT" ]; then
+if [ $SB2INIT_WITH_LOCALES == 1 ]; then
+	if [ -n "$SB2INIT_TOOLS_ROOT" ]; then
 		$SBOX_DIR/bin/sb2 -t $TARGET \
 		    $SBOX_DIR/share/scratchbox2/scripts/sb2-generate-locales -T
 	fi
 
-	if [ -z "$CPUTRANSP" ]; then
+	if [ -z "$SB2INIT_CPUTRANSP" ]; then
 		$SBOX_DIR/bin/sb2 -t $TARGET \
 		    $SBOX_DIR/share/scratchbox2/scripts/sb2-generate-locales
 	fi
 fi
 
-if [ $with_libtool == 1 ]; then
+if [ $SB2INIT_WITH_LIBTOOL == 1 ]; then
+	echo "sb2-init: configuring libtool for this target:"
 	$SBOX_DIR/bin/sb2 -t $TARGET $SBOX_DIR/bin/sb2-build-libtool
 	TEST=$?
 	printf "\n\n"
