Refactored configuration of DEB_* variables (incl. a bugfix)
DEB_* environment variables used to be in sb2.config (which is
written by sb2-init). Moved all of those to a separate configuration
file, sb2.config.d/debian.conf, which gets created by a new
script ("sb2-config-debian").

This has several advantages; first, the DEB_* variables can
now be re-created by the sb2-upgrade-config system. Second,
those variables are now created by running "dpkg-architecture"
whenever possible (previously they were invented by a built-in
logic in "sb2-init" - this is definitely not the correct way),
and third, this change makes "sb2" and "sb2-init" a little less
debian-specific, as the debian-related logic is now in a
separate script.

Also, this change fixes a bug with intel targets: DEB_* variables
were not configured correctly by sb2-init..

diff --git a/utils/sb2 b/utils/sb2
--- a/utils/sb2
+++ b/utils/sb2
@@ -61,6 +61,7 @@ Options:
     -C dir       When creating a session, create copy of "dir" and use it as the 
                  target_root (rootstrap).
     -T dir       use "dir" as tools_root (overriding the value from config file)
+    -u           Disable automatic configuration upgrade.
 
 Examples:
     sb2 ./configure
@@ -238,21 +239,39 @@ function load_configuration()
 	. ~/.scratchbox2/$SBOX_TARGET/sb2.config
 	LD_LIBRARY_PATH=$saved_LD_LIBRARY_PATH
 
+	# older sb2.config files had values for the Debian
+	# variables; unset them (this is necessary only if
+	# the target still has an old-format sb2.config)
+	unset DEB_BUILD_ARCH
+	unset DEB_BUILD_ARCH_CPU
+	unset DEB_BUILD_ARCH_ABI
+	unset DEB_BUILD_GNU_CPU
+	unset DEB_BUILD_GNU_TYPE
+	unset DEB_BUILD_GNU_SYSTEM
+	unset DEB_HOST_ARCH
+	unset DEB_HOST_ARCH_OS
+	unset DEB_HOST_ARCH_CPU
+	unset DEB_HOST_GNU_CPU
+	unset DEB_HOST_GNU_TYPE
+	unset DEB_HOST_GNU_SYSTEM
+
 	# Remember where SBOX_TARGET_ROOT was in the configuration file
 	SBOX_TARGET_ROOT_in_config_file=$SBOX_TARGET_ROOT
 
 	#-----------
 	# "New" config system stores configuration to various files
 	# in sb2.config.d directory, and the configuration is automatically
-	# upgraded whenever needed:
+	# upgraded whenever needed (unless prohibited by a command-line option):
 	
 	# check if we need to upgrade configuration:
-	if [ ! -f ~/.scratchbox2/$SBOX_TARGET/sb2.config.d/config-stamp.16 ]; then
-		$SBOX_DIR/share/scratchbox2/scripts/sb2-upgrade-config \
-			$SBOX_TARGET
-		if [ $? != 0 ]; then
-			echo "Failed to upgrade configuration files" >&2
-			exit 1
+	if [ -z "$OPT_DONT_UPGRADE_CONFIGURATION" ]; then
+		if [ ! -f ~/.scratchbox2/$SBOX_TARGET/sb2.config.d/config-stamp.17 ]; then
+			$SBOX_DIR/share/scratchbox2/scripts/sb2-upgrade-config \
+				$SBOX_TARGET
+			if [ $? != 0 ]; then
+				echo "Failed to upgrade configuration files" >&2
+				exit 1
+			fi
 		fi
 	fi
 
@@ -284,6 +303,14 @@ function load_configuration()
 	# to LD_LIBRARY_PATH here. Fakeroot will take care of adding it the
 	# the head, if it has been activated.
 	LD_LIBRARY_PATH="$HOST_LD_LIBRARY_PATH_PREFIX$HOST_LD_LIBRARY_PATH_LIBSB2$HOST_LD_LIBRARY_PATH_SUFFIX"
+
+	#-----------
+	# Get values for the DEB_* variables from the new config file:
+	if [ ! -f $HOME/.scratchbox2/$SBOX_TARGET/sb2.config.d/debian.conf ]; then
+		echo "Fatal: Failed to get Debian build system variables (config file does not exist)"
+		exit 1
+	fi
+	. $HOME/.scratchbox2/$SBOX_TARGET/sb2.config.d/debian.conf
 }
 
 function clone_target_root_dir_from()
@@ -1226,8 +1253,9 @@ OPT_CLONE_TARGET_ROOT="n"
 OPT_CLONE_TARGET_ROOT_FROM=""
 OPT_SESSION_DIR=""
 SBOX_FORCED_TOOLS_ROOT=""
+OPT_DONT_UPGRADE_CONFIGURATION=""
 
-while getopts vdht:em:s:L:Q:M:ZrRS:J:D:W:O:cC:T: foo
+while getopts vdht:em:s:L:Q:M:ZrRS:J:D:W:O:cC:T:u foo
 do
 	case $foo in
 	(v) version; exit 0;;
@@ -1253,6 +1281,7 @@ do
 	(c) OPT_CLONE_TARGET_ROOT="y" ;;
 	(C) OPT_CLONE_TARGET_ROOT_FROM=$OPTARG ;;
 	(T) SBOX_FORCED_TOOLS_ROOT=$OPTARG ;;
+	(u) OPT_DONT_UPGRADE_CONFIGURATION="y" ;;
 	(*) usage ;;
 	esac
 done
@@ -1407,21 +1436,6 @@ fi
 # ------------
 # Export variables that need to be available in environment;
 # don't export anything unnecessary!
-
-export DEB_BUILD_ARCH
-export DEB_BUILD_ARCH_CPU
-export DEB_BUILD_ARCH_ABI
-export DEB_BUILD_GNU_CPU
-export DEB_BUILD_GNU_TYPE
-export DEB_BUILD_GNU_SYSTEM
-
-export DEB_HOST_ARCH
-export DEB_HOST_ARCH_OS
-export DEB_HOST_ARCH_CPU
-
-export DEB_HOST_GNU_CPU
-export DEB_HOST_GNU_TYPE
-export DEB_HOST_GNU_SYSTEM
 
 export LD_LIBRARY_PATH
 
diff --git a/utils/sb2-init b/utils/sb2-init
--- a/utils/sb2-init
+++ b/utils/sb2-init
@@ -122,21 +122,6 @@ SBOX_CPU=$ARCH
 SBOX_CPUTRANSPARENCY_METHOD="$SB2INIT_CPUTRANSP"
 SBOX_UNAME_MACHINE=$MACHINE_ARCH
 
-DEB_BUILD_ARCH=$SB2INIT_DEB_BUILD_ARCH
-DEB_BUILD_ARCH_CPU=$SB2INIT_DEB_BUILD_ARCH_CPU
-DEB_BUILD_ARCH_ABI=$SB2INIT_DEB_BUILD_ARCH_ABI
-DEB_BUILD_GNU_CPU=$ARCH
-DEB_BUILD_GNU_TYPE=$SB2INIT_DEB_BUILD_GNU_TYPE
-DEB_BUILD_GNU_SYSTEM=$SB2INIT_DEB_BUILD_GNU_SYSTEM
-
-DEB_HOST_ARCH=$DEBIAN_CPU
-DEB_HOST_ARCH_OS=$SB2INIT_DEB_HOST_ARCH_OS
-DEB_HOST_ARCH_CPU=$SB2INIT_DEB_HOST_ARCH_CPU
-
-DEB_HOST_GNU_CPU=$ARCH
-DEB_HOST_GNU_TYPE=$SB2INIT_DEB_HOST_GNU_TYPE
-DEB_HOST_GNU_SYSTEM=$SB2INIT_DEB_HOST_GNU_SYSTEM
-
 SBOX_HOST_GCC_NAME=host-gcc
 SBOX_HOST_GCC_PREFIX_LIST=host-
 SBOX_HOST_GCC_SUBST_PREFIX=
@@ -322,30 +307,17 @@ else
 	echo "sb2-init: Target machine is '$SB2INIT_MACHINE_ARCH'"
 fi
 
-DEBIAN_CPU=$ARCH
-
 HOST_ARCH="$(uname -m)"
 if echo "$HOST_ARCH" | grep -q "^i.86*"; then
 	HOST_ARCH="i[3456]86"
 fi
 echo "sb2-init: Host architecture is '$HOST_ARCH'"
 
+DEFAULT_CPUTRANSP=""
 case "$ARCH" in
 	$HOST_ARCH*) ;;
 
-	arm*) 
-		# SBOX_GCC_TARGET from gcc.config.sh..
-		if [ -z "$SBOX_GCC_TARGET" ]; then
-			DEBIAN_CPU=$ARCH
-		else
-			echo $SBOX_GCC_TARGET | grep -q -i eabi
-			if [ $? == 0 ]; then
-				DEBIAN_CPU=armel
-			fi
-		fi
-		DEFAULT_CPUTRANSP="qemu-$ARCH"
-		;;
-
+	arm*)	DEFAULT_CPUTRANSP="qemu-$ARCH" ;;
 	ppc*)	DEFAULT_CPUTRANSP="qemu-$ARCH" ;;
 	mips*)	DEFAULT_CPUTRANSP="qemu-$ARCH" ;;
 	sh*)	DEFAULT_CPUTRANSP="qemu-$ARCH" ;;
@@ -398,26 +370,11 @@ if ! expr "$ARCH" : "$HOST_ARCH" > /dev/null ; then
 	fi
 fi
 
-# defaults for SB2_INIT_DEB_BUILD_GNU_TYPE, SB2_INIT_DEB_HOST_GNU_TYPE, etc,
-# and the cross-gcc prefix list:
-# these may be changed by sb2rc.$MAPPING_MODE
-SB2INIT_DEB_BUILD_ARCH=$DEBIAN_CPU
-SB2INIT_DEB_BUILD_ARCH_ABI="gnu"
-SB2INIT_DEB_BUILD_GNU_TYPE=$ARCH-linux-gnu
-SB2INIT_DEB_BUILD_GNU_SYSTEM=""
-SB2INIT_DEB_BUILD_ARCH_CPU=$DEBIAN_CPU
-
-SB2INIT_DEB_HOST_GNU_TYPE=$ARCH-linux-gnu
-SB2INIT_DEB_HOST_GNU_SYSTEM=""
-SB2INIT_DEB_HOST_ARCH_OS="linux"
-SB2INIT_DEB_HOST_ARCH_CPU=$DEBIAN_CPU
-
 # $ARCH has been set, get mode-specific settings..
 if [ -f $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE ]; then
 	echo "Reading mode-specific settings.."
 	. $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE "initializing"
 fi
-
 
 if [ ! $SB2INIT_SKIP_CHECKS ]; then
 	check_buildroot_sanity
@@ -455,8 +412,22 @@ if [ -n "$SB2INIT_REMOTEHOST" ]; then
 	write_sbrsh_config
 fi
 
+# ---------------------------
+# The target can be used now; it is possible to 
+# finalize the configuration by running programs in the new environment.
+
 if [ $SB2INIT_SET_AS_DEFAULT == 1 ]; then
 	sb2-config -d $TARGET
+fi
+
+# if the target system is (based on) debian,
+# DEB_* environment variables are needed. We'll set them in any case:
+echo "sb2-init: Creating Debian build system settings for this target:"
+$SBOX_DIR/share/scratchbox2/scripts/sb2-config-debian -t $TARGET
+if [ $? != 0 ]; then
+	log_config_action "sb2-init: failed run sb2-config-debian"
+	echo "sb2-init: sb2-config-debian failed."
+	exit 1
 fi
 
 #
