sb2: Fix errors found shellcheck SC2166, SC2181, SC2048 and SC2012
Remove useless checks like:
```
command
if [ $# -eq 0 ] ; then
    error
fi
```

Or replace obsolescent -a and -o with `[ ] && [ ] ` and `[ ] || [ ]`.

https://github.com/koalaman/shellcheck/wiki/SC2166
https://github.com/koalaman/shellcheck/wiki/SC2181

diff --git a/utils/sb2-session b/utils/sb2-session
--- a/utils/sb2-session
+++ b/utils/sb2-session
@@ -12,7 +12,7 @@
 # Licensed under GPL version 2
 #
 prog="$0"
-progbase=`basename $0`
+progbase=$(basename $prog)
 session_save_dir="$HOME/.scratchbox2/saved_sessions"
 
 usage()
@@ -104,8 +104,8 @@ END
 
 die()
 {
-	echo $1
-	exit $2
+	echo "$1" >&2
+	exit ${2:-1}
 }
 
 attach_session()
@@ -117,7 +117,7 @@ attach_session()
 		shift
 	fi
 
-	if [ -z "$session" -o "$session" = "--" ]; then
+	if [ -z "$session" ] || [ "$session" = "--" ]; then
 		#
 		# No session id given.  This means that there should
 		# only be one session and we should use that.
@@ -142,22 +142,23 @@ attach_session()
 
 save_session()
 {
-	echo -n "Session description: "
+	printf "%s" "Session description: "
 	read session_descr
 	write_session_info "$session_descr"
 }
 
 list_sessions()
 {
-	for s in $( ls $session_save_dir/session.* 2>/dev/null ); do
+    for s in $session_save_dir/session.* ; do
+		[ -e $s ] || continue
 		session_file=$(basename $s)
 		session_descr=$( grep SBOX_SESSION_DESCRIPTION $s | \
-		    sed 's/SBOX_SESSION_DESCRIPTION="\([^"]*\)"/\1/' )
+							 sed 's/SBOX_SESSION_DESCRIPTION="\([^"]*\)"/\1/' )
 		session_target=$( grep SBOX_TARGET $s | \
-		    sed 's/SBOX_TARGET=\([^"]*\)/\1/' )
+							  sed 's/SBOX_TARGET=\([^"]*\)/\1/' )
 		printf "%s\t%s\t%s\n" "$session_file" "$session_target" \
-		    "$session_descr"
-	done
+			   "$session_descr"
+    done
 }
 
 delete_session()
@@ -184,19 +185,16 @@ set_env_var()
 		mkdir -p "$SBOX_SESSION_DIR/env_vars"
 		echo "$varname=\"$value\"" >$SBOX_SESSION_DIR/env_vars/$varname
 	else
-		die "'sb2-session setenv' must be used inside existing session!" $?
+		die "'sb2-session setenv' must be used inside existing session!"
 	fi
 }
 
 show_env_vars()
 {
 	if [ $inside_sb2 -eq 1 ]; then
-		count=$( ls $SBOX_SESSION_DIR/env_vars/* 2>/dev/null | wc -l )
-		if [ "$count" -gt 0 ]; then
-			cat $SBOX_SESSION_DIR/env_vars/*
-		fi
+		find "$SBOX_SESSION_DIR/env_vars" -type f cat {} \;
 	else
-		die "'sb2-session showenv' must be used inside existing session!" $?
+		die "'sb2-session showenv' must be used inside existing session!"
 	fi
 }
 
@@ -209,7 +207,7 @@ shift
 
 if [ ! -e "$session_save_dir" ]; then
 	/bin/mkdir $session_save_dir 2>/dev/null ||
-	    die "unable to create session save directory: $saved_sessions_dir" $rc
+	    die "unable to create session save directory: $saved_sessions_dir" $?
 fi
 
 if [ -z "$SBOX_SESSION_DIR" ]; then
@@ -225,11 +223,9 @@ case "$command" in
 		;;
 	attach)
 		if [ $inside_sb2 -ne 0 ]; then
-			echo -n "'attach' command cannot be run from inside "
-			echo "sb2 session"
-			exit 1
+		    die "'attach' command cannot be run from inside sb2 session"
 		fi
-		attach_session $*
+		attach_session "${@}"
 		;;
 
 	save)
@@ -239,9 +235,7 @@ case "$command" in
 		# it.
 		#
 		if [ $inside_sb2 -ne 1 ]; then
-			echo -n "'save' command can only be run from inside "
-			echo "sb2 session"
-			exit 1
+		    die "'save' command can only be run from inside sb2 session"
 		fi
 
 		. $SBOX_SESSION_DIR/sb2-session.conf
@@ -255,16 +249,14 @@ case "$command" in
 
 	delete)
 		if [ $inside_sb2 -ne 0 ]; then
-			echo -n "'delete' command cannot be run from inside "
-			echo "sb2 session"
-			exit 1
+		    die "'delete' command cannot be run from inside sb2 session"
 		fi
 
 		delete_session "$1"
 		;;
 
 	setenv)
-		set_env_var $*
+		set_env_var "${@}"
 		;;
 
 	showenv)
@@ -272,5 +264,5 @@ case "$command" in
 		;;
 
 	*)
-		die "invalid command: $command" 1
+		die "invalid command: $command"
 esac
diff --git a/utils/sb2-upgrade-config b/utils/sb2-upgrade-config
--- a/utils/sb2-upgrade-config
+++ b/utils/sb2-upgrade-config
@@ -85,25 +85,24 @@ update_toolchain_configs()
 	else
 		gccconfig_arch_option2=""
 	fi
-	for compiler_path in $*; do
+	for compiler_path in "$@"; do
 		# echo "Updating compiler $compiler_path"
 		log_config_action "Config upgrade: settings for compiler $compiler_path"
-		$SBOX_SHARE_DIR/scripts/sb2-config-gcc-toolchain \
-			$secondary_compiler \
-			$gccconfig_arch_option \
-			$gccconfig_arch_option2 \
-			-R "$SB2INIT_TARGET_ROOT" \
-			-S "$SBOX_SHARE_DIR/../.." \
-			-t "$SB2INIT_TARGET" \
-			-m "$SB2INIT_MAPPING_MODE" \
-			-C "$SB2INIT_SBOX_EXTRA_CROSS_COMPILER_ARGS" \
-			-L "$SB2INIT_SBOX_EXTRA_CROSS_LD_ARGS" \
-			-- \
-			$compiler_path
-		if [ $? != 0 ]; then
-			log_config_action "failed to configure $compiler_path"
-			echo "Failed to configure $compiler_path"
-			exit 1
+		if ! $SBOX_SHARE_DIR/scripts/sb2-config-gcc-toolchain \
+		     $secondary_compiler \
+		     $gccconfig_arch_option \
+		     $gccconfig_arch_option2 \
+		     -R "$SB2INIT_TARGET_ROOT" \
+		     -S "$SBOX_SHARE_DIR/../.." \
+		     -t "$SB2INIT_TARGET" \
+		     -m "$SB2INIT_MAPPING_MODE" \
+		     -C "$SB2INIT_SBOX_EXTRA_CROSS_COMPILER_ARGS" \
+		     -L "$SB2INIT_SBOX_EXTRA_CROSS_LD_ARGS" \
+		     -- $compiler_path
+		then
+		    log_config_action "failed to configure $compiler_path"
+		    echo "Failed to configure $compiler_path"
+		    exit 1
 		fi
 		secondary_compiler="-V"
 	done
@@ -164,7 +163,7 @@ update_debian_config()
 }
 
 if [ ! -d $SBOX_CONFIG_DIR ]; then
-	mkdir $SBOX_CONFIG_DIR 
+	mkdir $SBOX_CONFIG_DIR
 	log_config_action "Config upgrade: Created configuration directory"
 fi
 
