sb2-init can generate sbrsh config files

diff --git a/utils/sb2-init b/utils/sb2-init
--- a/utils/sb2-init
+++ b/utils/sb2-init
@@ -19,6 +19,8 @@ COMPILER is of the form $HOME/arm-2006q3/bin/arm-linux-gcc
 
 Options:
     -c [qemu | sbrsh] select cpu transparency method, qemu is default
+    -r [hostname]     generate sbrsh config using remote device address
+    -l [hostname]     NFS server/localhost address seen by remote device
     -d                set target as default scratchbox2 target
     -h                print this help
     -n                don't build libtool for the target
@@ -47,7 +49,7 @@ function write_target_config()
 export SBOX_TARGET_ROOT=$SBOX_TARGET_ROOT
 export SBOX_CPU=$ARCH
 export SBOX_GCC_TARGET=$GCC_TARGET
-export SBOX_CPUTRANSPARENCY_METHOD=$QEMU
+export SBOX_CPUTRANSPARENCY_METHOD=$CPUTRANSP
 export SBOX_UNAME_MACHINE=$ARCH
 
 export SBOX_DEFAULT_GCC_PREFIX=$GCC_PREFIX
@@ -75,8 +77,27 @@ export SBOX_HOST_GCC_SUBST_PREFIX=
 export SBOX_HOST_GCC_SPECS_FILE=
 export SBOX_HOST_GCC_DIR=/usr/bin
 export SBOX_HOST_GCC_LD_ARGS=
+
+export SBRSH_CONFIG=$HOME/.scratchbox2/$TARGET/sbrsh.config
 EOF
 	echo "Finished writing sb2.config"
+}
+
+function write_sbrsh_config()
+{
+	cat - > $HOME/.scratchbox2/$TARGET/sbrsh.config <<EOF
+# sbrsh configuration file generated by sb2-init.
+
+$TARGET  $REMOTEHOST
+  nfs   $LOCALHOST:$SBOX_TARGET_ROOT  /  rw,nolock,noac,tcp
+  nfs   $LOCALHOST:$HOME  /home  rw,nolock,noac,tcp
+  bind  /tmp      /tmp
+  bind  /proc     /proc
+  bind  /sys      /sys
+  bind  /dev      /dev
+  bind  /dev/pts  /dev/pts
+EOF
+	echo "Finished writing sbrsh.config"
 }
 
 function check_buildroot_sanity()
@@ -111,6 +132,9 @@ you can re-run this script."
 
 SBOX_DIR=$(readlink -f $(dirname $_)/..)
 
+REMOTEHOST=
+LOCALHOST=
+
 set_as_default=0
 cputransparency=qemu
 with_libtool=1
@@ -120,10 +144,12 @@ if [ -z "$*" ]; then
 	usage
 fi
 
-while getopts c:dhnsv foo
+while getopts c:r:l:dhnsv foo
 do
 	case $foo in
 	(c) cputransparency=$OPTARG ;;
+	(r) REMOTEHOST=$OPTARG ;;
+	(l) LOCALHOST=$OPTARG ;;
 	(d) set_as_default=1 ;;
 	(h) usage ;;
 	(n) with_libtool=0 ;;
@@ -133,6 +159,10 @@ do
 	esac
 done
 shift $(($OPTIND - 1))
+
+if [ "$LOCALHOST" ] && [ -z "$REMOTEHOST" ]; then
+	echo "Warning: Local host specified without remote host."
+fi
 
 TARGET=$1
 SBOX_TARGET_ROOT=$PWD
@@ -176,11 +206,35 @@ case "$ARCH" in
 esac
 
 
-QEMU=$(which qemu-$ARCH)
-if [ ! $skip_checks -a $? != 0 ]; then
-	echo "You don't have qemu-$ARCH installed."
-	exit 1
-fi
+case "$cputransparency" in
+qemu)
+	if ! $skip_checks && [ "$REMOTEHOST" ]; then
+		echo "Warning: QEMU and remote host specified at the same time."
+	fi
+
+	CPUTRANSP=$(which qemu-$ARCH)
+	if [ ! $skip_checks -a $? != 0 ]; then
+		echo "You don't have qemu-$ARCH installed."
+		exit 1
+	fi
+	;;
+
+sbrsh)
+	CPUTRANSP=$(which sbrsh)
+	if [ ! $skip_checks -a $? != 0 ]; then
+		echo "You don't have sbrsh installed."
+		exit 1
+	fi
+	;;
+
+*)
+	CPUTRANSP=$cputransparency
+	if [ ! $skip_checks ] && [ -x $CPUTRANSP ]; then
+		echo "Executable not found: $cputransparency"
+		exit 1
+	fi
+	;;
+esac
 
 if [ -z "$GCC" -o -z "$TARGET" ]; then
 	usage
@@ -204,6 +258,16 @@ fi
 
 mkdir -p $HOME/.scratchbox2/$TARGET/bin
 write_target_config
+
+if [ "$REMOTEHOST" ]; then
+	if [ -z "$LOCALHOST" ]; then
+		LOCALHOST=$(ip -f inet -o addr \
+			| awk -- '/: eth[0-9]/ { print $4; exit }' \
+			| cut -d/ -f1)
+		echo "Using NFS server address: $LOCALHOST"
+	fi
+	write_sbrsh_config
+fi
 
 if [ $set_as_default == 1 ]; then
 	sb2-config -d $TARGET
